# Build configuration for Feather nRF52840 mouse

board:
  - nrfmicro/nrf52840   # your Feather board target

shield:
  - none      # no additional shield needed for the mouse

overlays:
  - boards/shields/fthr840.overlay  # your overlay file path
