# Build configuration for Feather nRF52840 mouse

board:
  - adafruit_feather_nrf52840_express   # your Feather board target

shield:
  - none      # no additional shield needed for the mouse

overlays:
  - boards/shields/fthr840.overlay  # your overlay file path
